openapi: 3.0.0
info:
  title: API de Artículos
  description: Documentación de los endpoints relacionados con artículos
  version: 1.0.0

components:
  schemas:
    InternalServerErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
        error: 
          type: string
          example: "Error interno del servidor"
    SuccessfullLoginResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        message:
          type: string
          example: "Logged in"
        data:
            type: object
            properties:
              token:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQzMzY2ODAzLCJleHAiOjE3NDMzNzQwMDN9.GNcz2X4ivMtqnGC3aEF4tGU3jtbJl9ih1P8AaOQM2JE"

paths:
  /auth/login:
    post:
      summary: Autenticarse en el sistema
      tags:
        - Autenticación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Nombre del usuario administrador
                  example: "admin"
                password:
                  type: string
                  description: Contraseña del administrador
                  example: "Admin123"
      responses:
        200:
          description: Autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessfullLoginResponse"
        401:
          description: No autorizado, credenciales inválidas
        403:
          description: Prohibido por CORS
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerErrorResponse"